---
- name: MongoDB | Enable on Startup
  command: sudo systemctl enable mongod.service
  ignore_errors: true

- name: MongoDB | Insure deamon is running correctly
  service: name=mongod state=restarted

